Add controllers
ruste4/java-shareit pull request #1
Opened 2022-07-07 23:42 UTC by ruste4

2022-07-09 10:47 UTC, kukolev requested changes

2022-07-09 10:47 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    "Owner with id:" + ownerId + " not found for item \"" + itemName + "\""
Тут лучше использовать String.format(...). Так код будет проще читаться.

2022-07-10 05:37 UTC, ruste4 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                    "Owner with id:" + ownerId + " not found for item \"" + itemName + "\""
Исправил в классах UserService и в ItemStorageImpl

2022-07-10 08:42 UTC, kukolev approved these changes

2022-07-10 16:40 UTC, merged