Add bookings
ruste4/java-shareit pull request #2
Opened 2022-07-28 06:30 UTC by ruste4

2022-07-28 17:37 UTC, kukolev requested changes

2022-07-28 17:37 UTC, kukolev commented on docker-compose.yml
> +#      PGDATA: "/var/lib/postgresql/data/pgdata"
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-28 17:37 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
По моему тут нужно использовать `@EqualsAndHashCode`, но при этом настроив исключения для полей. Тогда можно будет не писать equals и hashCode.

2022-07-28 17:37 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public int hashCode() {
Здесь нарушается контракт equals и hashCode. Фактически у всех объектов будет один и тот-же хэшкод, который не зависит от полей. Это нужно обязательно поправить. Именно по этому лучше использовать `@EqualsAndHashCode`

P.S. Рекомендую почитать про контракт тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-07-28 17:37 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    public int hashCode() {
Здесь нарушается контракт equals и hashCode. Фактически у всех объектов будет один и тот-же хэшкод, который не зависит от полей. Это нужно обязательно поправить. Именно по этому лучше использовать @EqualsAndHashCode

P.S. Рекомендую почитать про контракт тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-07-28 17:37 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public int hashCode() {
Здесь нарушается контракт equals и hashCode. Фактически у всех объектов будет один и тот-же хэшкод, который не зависит от полей. Это нужно обязательно поправить. Именно по этому лучше использовать @EqualsAndHashCode

P.S. Рекомендую почитать про контракт тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-07-28 17:37 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/User.java
> +    public int hashCode() {
Здесь нарушается контракт equals и hashCode. Фактически у всех объектов будет один и тот-же хэшкод, который не зависит от полей. Это нужно обязательно поправить. Именно по этому лучше использовать @EqualsAndHashCode

P.S. Рекомендую почитать про контракт тут: https://javarush.ru/groups/posts/1989-kontraktih-equals-i-hashcode-ili-kak-ono-vsje-tam

2022-07-28 21:03 UTC, ruste4 commented on docker-compose.yml
> +#      PGDATA: "/var/lib/postgresql/data/pgdata"
Исправил

2022-07-28 21:12 UTC, ruste4 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (status.equals("All")) {
исправил

2022-07-28 21:12 UTC, ruste4 commented on src/main/resources/application.properties
> +#spring.jpa.database=POSTGRESQL
исправил

2022-07-28 21:17 UTC, ruste4 commented on src/main/resources/application.properties
> +#logging.level.org.springframework.orm.jpa=INFO
исправил

2022-07-28 21:17 UTC, ruste4 commented on docker-compose.yml
> +#      PGDATA: "/var/lib/postgresql/data/pgdata"
исправил

2022-07-31 13:53 UTC, ruste4 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
Исправил без использования @EqualsAndHashCode

2022-07-31 13:53 UTC, ruste4 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public int hashCode() {
Исправил без использования @EqualsAndHashCode

2022-08-02 22:06 UTC, kukolev approved these changes

2022-08-05 09:36 UTC, merged