Add item requests
ruste4/java-shareit pull request #3
Opened 2022-08-08 21:01 UTC by ruste4

2022-08-09 16:36 UTC, kukolev requested changes

2022-08-09 16:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/requests/RequestServiceImp.java
> +public class RequestServiceImp implements RequestService {
По моему здесь опечатка в названии класса. Обычно пишут Impl в конце. Нужно поправить, если это опечатка.

2022-08-09 16:36 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/RequestServiceImpTest.java
> +                        String.format("Трейтий запрос должен быть %s", itemRequestDto1)
Орфографическая ошибка в слове «Третий». Нужно исправить.

2022-08-09 16:36 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/RequestServiceImpTest.java
> +                        String.format("Второй эелемент должен быть %s", itemRequestDto3)
Орфографическая ошибка в слове «элемент». Нужно исправить.

2022-08-09 16:36 UTC, kukolev commented on src/test/java/ru/practicum/shareit/requests/RequestServiceImpTest.java
> +                        String.format("Трейтий элемент должен быть %s", itemRequestDto2)
Орфографическая ошибка в слове «Третий». Нужно исправить.

2022-08-09 16:36 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    @Test
Эти тесты пустые. В таком виде они не нужны. Нужно дописать тесты.

2022-08-10 10:41 UTC, ruste4 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Исправил

2022-08-10 10:43 UTC, ruste4 commented on src/main/java/ru/practicum/shareit/requests/RequestServiceImp.java
> +public class RequestServiceImp implements RequestService {
Испрвил

2022-08-10 10:44 UTC, ruste4 commented on src/test/java/ru/practicum/shareit/requests/RequestServiceImpTest.java
> +                        String.format("Трейтий запрос должен быть %s", itemRequestDto1)
Исправил

2022-08-10 10:45 UTC, ruste4 commented on src/test/java/ru/practicum/shareit/requests/RequestServiceImpTest.java
> +                        String.format("Второй эелемент должен быть %s", itemRequestDto3)
Исправил

2022-08-10 10:46 UTC, ruste4 commented on src/test/java/ru/practicum/shareit/requests/RequestServiceImpTest.java
> +                        String.format("Трейтий элемент должен быть %s", itemRequestDto2)
Исправил

2022-08-11 11:23 UTC, ruste4 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    @Test
добавил

2022-08-11 22:33 UTC, kukolev requested changes
Не выполнено требование ТЗ: Нужно добавить пагинацию в эндпоинты GET /items, GET /items/search, GET /bookings и GET /bookings/owner

2022-08-16 21:44 UTC, kukolev approved these changes

2022-08-17 12:11 UTC, merged